### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by geosskk** [NanoAi/gm_pug#2] opened 2020-04-07 01:56 UTC
Feature 1:
Allow for props that are welded to each other to be moved when ghosting is on.
Feature 2:
Toggle vehicle collisions with players and other vehicles.

**Comment by NanoAi** [comment] 2020-04-07 08:16
Duplicate of #1 

I have reopened #1 no need to make a new issue, we can just continue in there for cleanliness and clarity. :)

**Closed as completed by NanoAi** 2020-04-07 08:16 UTC
Labels: duplicate
